# frozen_string_literal: true

source 'https://rubygems.org'
gem 'berkshelf'
gem 'bump'
gem 'chef', '~> 14'
gem 'chefspec-ohai'
gem 'cookstyle', '~> 5.22'
gem 'foodcritic'
gem 'java-properties'
gem 'kitchen-dokken'
gem 'kitchen-inspec'
gem 'kitchen-nodes'
gem 'kitchen-vagrant'
gem 'knife-cookbook-doc'
gem 'rake'
gem 'rspec_junit_formatter'
gem 'rubocop-checkstyle_formatter', require: false
gem 'simplecov'
gem 'simplecov-cobertura'
gem 'stove'
gem 'test-kitchen'
gem 'vagrant-berkshelf'
gem 'vault'
gem 'yard'
gem 'yard-chef'
